services:
  threaded_server:
    build:
      context: ./vulnerable-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
      - "2222:22"
    container_name: threaded_server_container
    networks:
      - my_network

  hello_world_container:
    build:
      context: ./hello-server
    container_name: hello_world_container
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
