services:
  threaded_server:
    build:
      context: ./vulnerable-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9091:9091"
      - "2222:22"
    container_name: threaded_server_container

  hello_world:
    build:
      context: ./vulnerable-server
      dockerfile: Dockerfile
    container_name: hello_world_container
